apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:latest
          ports:
            - containerPort: 3306
              name: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: root-password
           
            - name: MYSQL_USER
              value: "admin"
            
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: mysql-password
            
            - name: MYSQL_ROOT_HOST
              value: "mysql-service"
            
            - name: MYSQL_DATABASE
              value: "employees"
          
          volumeMounts:
            - name: init-script
              mountPath: /docker-entrypoint-initdb.d
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "1"
              memory: "512Mi"
          livenessProbe:
            tcpSocket:
              port: 3306
            initialDelaySeconds: 10
            periodSeconds: 15
          readinessProbe:
            exec:
              command:
                - mysqladmin
                - ping
                - "-h"
                - "127.0.0.1"
            initialDelaySeconds: 5
            periodSeconds: 10
      volumes:
        - name: init-script 
          configMap:
            name: mysql-init-sql

---

apiVersion: v1
kind: Service 
metadata: 
  name: mysql-service
spec:
  selector:
    app: mysql
  type: ClusterIP
  ports:
    - name: mysql-port
      port: 3306
      targetPort: 3306
      protocol: TCP
