name: Build and Push Docker Image

on:
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main 

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build ./docker-compose-mysql-webapp/webapp -t ${{ secrets.DOCKER_USERNAME }}/flask-web-1:${{ github.sha }} 

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/flask-web-1:${{ github.sha }}

      - name: Update Image
        run: |
          cd ./kubernetes-bonus
          # Update the image tag in your deployment.yaml
          sed -i "s|image: .*|image: ${{ secrets.DOCKER_USERNAME }}/flask-web-1:${{ github.sha }}|" flask-new-deployment.yml

          
      - name: Commit changes
        run: |
          git config --global user.email "${{ secrets.EMAIL_GITHUB }}"
          git config --global user.name "${{ secrets.USERNAME_GITHUB }}"
          git add ./kubernetes-bonus/flask-new-deployment.yml
          git commit -m "update image tag to ${{ github.sha }}"
           git push https://x-access-token:${{ secrets.MY_GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:${{ github.ref }} --force